### ISSUE TITLE
Hardcoded proxmox node name

### ISSUE THREAD

**Issue by christophe-lucas** [rgl/terraform-proxmox-talos#3]
Proxmox node name is hardcoded in this file:

https://github.com/rgl/terraform-proxmox-talos/blob/46508a59caeea42c035f1307add0544c268cc537/proxmox.tf#L16

**Comment by rgl** [comment]
fixed in https://github.com/rgl/terraform-proxmox-talos/commit/b24485b9eeb45f7245f3f5315a772a184511395b.

thank you!
