### ISSUE TITLE
Invalid variable description

### ISSUE THREAD

**Issue by christophe-lucas** [rgl/terraform-proxmox-talos#4]
Description is about cluster name whereas variable is about talos VIP
https://github.com/rgl/terraform-proxmox-talos/blob/46508a59caeea42c035f1307add0544c268cc537/variables.tf#L41

**Comment by rgl** [comment]
fixed in https://github.com/rgl/terraform-proxmox-talos/commit/7e485399dae67f1b658b3e717f046783984609fc.

thank you!
